[package]
name = "reddit-mbti-data-aggregator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
roux = "2.2.1"
rpassword = "0.0.4"
reqwest = "0.11.11"
